### ISSUE TITLE
no module `monolithic` ?

### ISSUE THREAD

**Issue by larrycai** [Djiit/err-jenkins#10]
When I install the dependance `pip3 install -r requirements.txt`

I got error below 

<pre>
Collecting python-jenkins (from -r requirements.txt (line 1))
  Using cached python-jenkins-0.4.14.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/app/venv/lib/python3.4/site-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/app/venv/lib/python3.4/site-packages/pbr/util.py", line 267, in cfg_to_args
        wrap_commands(kwargs)
      File "/app/venv/lib/python3.4/site-packages/pbr/util.py", line 569, in wrap_commands
        cmdclass = ep.resolve()
      File "/app/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2309, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named 'monolithic'
    error in setup command: Error parsing /tmp/pip-build-4vk5ya8i/python-jenkins/setup.cfg: ImportError: No module named 'monolithic'
</pre>

**Comment by Djiit** [comment]
Seems related to https://github.com/errbotio/errbot/issues/998
